# Naive Bayes

Naive Bayes methods are a set of supervised learning algorithms based on applying Bayes' theorem with the "naive" assumption of conditional independence between every pair of features given the value of the class variable. Bayes'theorem states the following relationship, given class variable $y$ and dependent feature vector $x_1$ through $x_n$,:

$$P(y \mid x_1, \dots, x_n) = \frac{P(y) P(x_1, \dots x_n \mid y)}
                                 {P(x_1, \dots, x_n)}$$

Using the naive conditional independence assumption, we have

$$\begin{align}\begin{aligned}P(y \mid x_1, \dots, x_n) \propto P(y) \prod_{i=1}^{n} P(x_i \mid y)\\\Downarrow\\\hat{y} = \arg\max_y P(y) \prod_{i=1}^{n} P(x_i \mid y),\end{aligned}\end{align}$$

Then, we can use Maximum A Posteriori (MAP) estimation to estimate $P(y)$ and $P(x_i \mid y)$; the former is then the relative frequency of class $y$ in the training set.

*References*:
H. Zhang (2004). The optimality of Naive Bayes. Proc. FLAIRS.

# 1 Gaussian Naive Bayes

GaussianNB implements the Gaussian Naive Bayes algorithm for classification.   
The likelihood of the features is assumed to be Gaussian:

$$P(x_i \mid y) = \frac{1}{\sqrt{2\pi\sigma^2_y}} \exp\left(-\frac{(x_i - \mu_y)^2}{2\sigma^2_y}\right)$$

The parameters $\sigma_y$ and $\mu_y$  are estimated using maximum likelihood.

**Example** - The training data is generated as follows:

In [5]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

**Q1**: Training a GaussianNB model:

In [6]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X, Y)

GaussianNB(priors=None, var_smoothing=1e-09)

**Q2**: Predict the label of a data [-0.8,-1]:

In [7]:
X_test = np.array([[-0.8, -1]])
print(gnb.predict(X_test))

[1]


# 2 MultinomialNB

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). 

*References*   
C.D. Manning, P. Raghavan and H. Schuetze (2008). Introduction to Information Retrieval. Cambridge University Press, pp. 234-265. http://nlp.stanford.edu/IR-book/html/htmledition/naive-bayes-text-classification-1.html

**Example** - The training data is generated as follows:

In [8]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

**Q3**: Training a MultinomialNB model:

In [9]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

**Q4**: Predict the label of a data X[2:3]:

In [10]:
mnb.predict(X[3:4])

array([4])

# 3 Process on 'Iris' Data

In Week 9, we have studied how to use KNN algorithm to do classification task on 'iris' data. Here,we are going to employ the GaussianNB to conduct the same task. 

In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris_dataset = load_iris()
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=142)

In [12]:
print("X_train: ", X_train.shape)
print("y_train: ", y_train.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train:  (112, 4)
y_train:  (112,)
X_test:  (38, 4)
y_test:  (38,)


In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
gnb = GaussianNB()
# fit the model
gnb.fit(X_train, y_train)
# prediction on training set
y_pred_train = gnb.predict(X_train)
# predictions on test set
y_pred_test = gnb.predict(X_test)
# confusion matrix
print("Confusion matrix on train set: ")
print(confusion_matrix(y_test, y_pred_test))

Confusion matrix on train set: 
[[ 7  0  0]
 [ 0 15  2]
 [ 0  2 12]]


**Q5**：Report the acuracy result on test data:

In [14]:
print("acc train: ", accuracy_score(y_train, y_pred_train))
print("acc test: ", accuracy_score(y_test, y_pred_test))

acc train:  0.9821428571428571
acc test:  0.8947368421052632


# 4 Predict Human Activity Recognition (HAR)

The objective of this practice exercise is to predict current human activity based on phisiological activity measurements from 53 different features based in the [HAR dataset](http://groupware.les.inf.puc-rio.br/har#sbia_paper_section). The training (`har_train.csv`) and test (`har_validate.csv`) datasets are provided.

**Q6**: Build a Naive Bayes model, predict on the test dataset and compute the [confusion matrix](https://towardsdatascience.com/understanding-confusion-matrix-a9ad42dcfd62). Note: Please refer to the [`sklearn.metrics.confusion_matrix`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)

In [15]:
import pandas as pd

train = pd.read_csv('data\har_train.csv')
validate = pd.read_csv('data\har_validate.csv')
print("train shape: ", train.shape)
print("validate shape: ", validate.shape)

train shape:  (13737, 53)
validate shape:  (5885, 53)


In [16]:
set(train['classe'])

{'A', 'B', 'C', 'D', 'E'}

In [26]:
X_train = train.drop(['classe'], axis=1)
y_train = train['classe']
X_test = validate.drop(['classe'], axis=1)
y_test = validate['classe']
print("X_train shape: ", X_train.shape)
print("y_train shape: ", y_train.shape)
print("X_test shape: ", X_test.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (13737, 52)
y_train shape:  (13737,)
X_test shape:  (5885, 52)
y_test shape:  (5885,)


## GaussianNB Classifier

In [32]:
gnb = GaussianNB()
# fit the model
gnb.fit(X_train, y_train)
# prediction on training set
y_pred_train = gnb.predict(X_train)
# predictions on test set
y_pred_test = gnb.predict(X_test)
# calculating accuracies
print("acc train: ", accuracy_score(y_train, y_pred_train))
print("acc test: ", accuracy_score(y_test, y_pred_test))
# confusion matrix
print("\n")
print("Confusion matrix on train set: ")
print(confusion_matrix(y_test, y_pred_test))
print("\n")

acc train:  0.5580548882579893
acc test:  0.5542905692438402


Confusion matrix on train set: 
[[1070   95  262  212   35]
 [ 127  685  145   76  106]
 [ 223  106  512  136   49]
 [ 102   35  271  441  115]
 [  51  239   95  143  554]]




In [33]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, y_train)

y_pred_train = model.predict(X_train)

y_pred_test = model.predict(X_test)

print("acc on train: ", accuracy_score(y_train, y_pred_train))
print("acc on train: ", accuracy_score(y_test, y_pred_test))

acc on train:  0.9552303996505788
acc on train:  0.9097706032285472
